### ISSUE TITLE
Errent equal sign in macro

### ISSUE THREAD

**Issue by wildj79** [Valien/foundryvtt#2]
https://github.com/Valien/foundryvtt/blob/0187c16e5368d7611f98624bc9e3e9402ec4eff1/macros/wandering_monsters.js#L11

The above is wrong. Should be `sound: CONFIG.sounds.dice`. There shouldn't be an equal sign in an object property.

**Comment by Valien** [comment]
Thanks! I'm no JS guru so appreciate the correction! Has been resolved.
